### PR TITLE
change ggplot2 movies

### PR DESCRIPTION
**Pull request by zachcp**
the movies dataset is now packaged in the `ggplot2movies` package

### CODE REVIEW

**Comment by timelyportfolio** [comment]
Thanks so much.  I need to circle back and revisit this, since I think some other JavaScript things are broken now.

**Comment by zachcp** [comment]
this is a great idea. before stumbling across it I coded up something similar (but more hackish.) I think this would be particularly useful in the context of Shingy Gadgets. A shiny button could then trigger the PNG. (my main beef with the current setup is the download icon.)

**Comment by timelyportfolio** [comment]
Great idea with Shiny gadgets.  I spent no time on the icon.  I grabbed it from FontAwesome and insert in these [lines](https://github.com/timelyportfolio/exportwidget/blob/master/inst/htmlwidgets/export_widget.js#L158-L161).  We could easily allow this to be customized or use other icon sets.

You have sufficiently motivated me.  Hopefully, I can get this back up and running by the end of the week.

**Comment by zachcp** [comment]
i wish it was always this easy to inspire someone else to do work you would like to see done (smiley emoticon)

**Pull request merged**
